export default {
  "en": {
    "title": "Health publications",
    "intro": "Understand a subject at your own pace. Explore our collection by category and read each article online.",
    "browse": "Browse by category",
    "breadcrumb": "Breadcrumb",
    "forwardArrow": "→",
    "backArrow": "←",
    "navigation": "Browse publications",
    "articles": "articles",
    "read": "min read",
    "explore": "Explore category",
    "start": "Start here",
    "contents": "In this article",
    "by": "By",
    "source": "About this publication",
    "translated": "English translation of the author’s French publication.",
    "original": "Read the French original",
    "sourceLabel": "Source document",
    "disclaimer": "This publication is provided for educational information and does not replace individual advice from a qualified healthcare professional.",
    "related": "Continue exploring",
    "previous": "Previous in this category",
    "next": "Next in this category",
    "back": "Back to category",
    "bookLabel": "From the Family Clinic bookshelf",
    "bookTitle": "Cooking to Heal",
    "bookDescription": "Explore a selection of recipes from the book, with ingredients and step-by-step instructions you can read online.",
    "bookAction": "Explore 20 recipe excerpts",
    "countDescription": "Articles in the collection’s reading order.",
    "translatedLabel": "English translation",
    "bookIntro": "Discover 20 recipes from Cooking to Heal, a collection of 200 recipes by Dr. Said-Alaoui Moulay Abdellah. Read the ingredients, follow each step, and bring these ideas into your own kitchen.",
    "recipeTitle": "Recipe excerpts",
    "recipe": "Recipe",
    "bookCover": "Cooking to Heal book cover",
    "preface": "Read the author’s preface",
    "nutritionNotes": "The author’s nutrition notes",
    "healthGoal": "Health goal",
    "benefits": "Benefits",
    "nutrition": "Nutrition",
    "preparation": "Preparation",
    "ingredients": "Ingredients",
    "servings": "Servings",
    "time": "Time",
    "tip": "Tip",
    "variation": "Variation",
    "print": "Print recipe",
    "recipeBack": "All recipe excerpts",
    "recipeSource": "From Cooking to Heal, English edition",
    "contact": "Have a question about your own care?",
    "contactLink": "Contact the clinic",
    "overview": "Start with the category overview or choose the subject that interests you."
  },
  "fr": {
    "title": "Publications santé",
    "intro": "Explorez les publications par catégorie et lisez chaque article à votre rythme.",
    "browse": "Parcourir par catégorie",
    "breadcrumb": "Fil d’Ariane",
    "forwardArrow": "→",
    "backArrow": "←",
    "navigation": "Parcourir les publications",
    "articles": "articles",
    "read": "min de lecture",
    "explore": "Explorer la catégorie",
    "start": "Pour commencer",
    "contents": "Dans cet article",
    "by": "Par",
    "source": "À propos de cette publication",
    "translated": "",
    "original": "Lire la version originale",
    "sourceLabel": "Document source",
    "disclaimer": "Cette publication est fournie à titre informatif et éducatif et ne remplace pas l’avis individuel d’un professionnel de santé qualifié.",
    "related": "Poursuivre votre lecture",
    "previous": "Article précédent",
    "next": "Article suivant",
    "back": "Retour à la catégorie",
    "bookLabel": "La bibliothèque de Family Clinic",
    "bookTitle": "Cuisiner pour guérir",
    "bookDescription": "Découvrez une sélection de recettes du livre, avec les ingrédients et les étapes de préparation à lire en ligne.",
    "bookAction": "Explorer 20 recettes du livre",
    "bookIntro": "Découvrez 20 recettes de Cuisiner pour guérir, un recueil de 200 recettes du Dr Said-Alaoui Moulay Abdellah. Consultez les ingrédients, suivez les étapes et essayez ces idées dans votre cuisine.",
    "recipeTitle": "Extraits de recettes",
    "recipe": "Recette",
    "bookCover": "Couverture de Cuisiner pour guérir",
    "preface": "Lire la préface de l’auteur",
    "nutritionNotes": "Les notes nutritionnelles de l’auteur",
    "healthGoal": "Objectif santé",
    "benefits": "Bienfaits",
    "nutrition": "Nutrition",
    "preparation": "Préparation",
    "ingredients": "Ingrédients",
    "servings": "Portions",
    "time": "Temps",
    "tip": "Astuce",
    "variation": "Variante",
    "print": "Imprimer la recette",
    "recipeBack": "Tous les extraits de recettes",
    "countDescription": "Articles dans l’ordre de la collection.",
    "translatedLabel": "",
    "contact": "Une question concernant votre santé ?",
    "contactLink": "Contactez la clinique",
    "overview": "Commencez par la présentation générale ou choisissez le sujet qui vous intéresse."
  },
  "ar": {
    "title": "المنشورات الصحية",
    "intro": "تعرّف على المواضيع الصحية بالوتيرة التي تناسبك. تصفّح منشوراتنا حسب الفئة واقرأ كل مقال مباشرة على الموقع.",
    "browse": "تصفّح حسب الفئة",
    "breadcrumb": "مسار التصفح",
    "forwardArrow": "←",
    "backArrow": "→",
    "navigation": "تصفّح المنشورات",
    "articles": "المقالات",
    "read": "دقيقة للقراءة",
    "explore": "استكشف الفئة",
    "start": "ابدأ هنا",
    "contents": "في هذا المقال",
    "translatedLabel": "ترجمة عربية",
    "related": "تابع القراءة",
    "previous": "المقال السابق في هذه الفئة",
    "next": "المقال التالي في هذه الفئة",
    "back": "العودة إلى الفئة",
    "bookLabel": "من مكتبة عيادة الأسرة",
    "bookTitle": "الطبخ للشفاء",
    "bookDescription": "اكتشف وصفات مختارة من الكتاب، مع المكونات وخطوات التحضير التي يمكنك قراءتها مباشرة على الموقع.",
    "bookAction": "استكشف 20 وصفة من الكتاب",
    "bookIntro": "اكتشف 20 وصفة من «الطبخ للشفاء»، وهو كتاب يضم 200 وصفة للدكتور سعيد العلوي مولاي عبد الله. تعرّف على المكونات، واتّبع خطوات التحضير، وجرّب هذه الأفكار في مطبخك.",
    "recipeTitle": "وصفات مختارة من الكتاب",
    "recipe": "الوصفة",
    "bookCover": "غلاف كتاب الطبخ للشفاء",
    "preface": "اقرأ مقدمة المؤلف",
    "nutritionNotes": "ملاحظات المؤلف حول التغذية",
    "healthGoal": "الهدف الصحي",
    "benefits": "الفوائد",
    "nutrition": "التغذية",
    "preparation": "طريقة التحضير",
    "ingredients": "المكونات",
    "servings": "الحصص",
    "time": "الوقت",
    "tip": "نصيحة",
    "variation": "بديل",
    "print": "طباعة الوصفة",
    "recipeBack": "جميع وصفات الكتاب المختارة",
    "contact": "لديك سؤال يخص صحتك؟",
    "contactLink": "تواصل مع العيادة",
    "disclaimer": "هذا المنشور للتثقيف والمعلومات العامة، ولا يحل محل المشورة الفردية من مختص مؤهل في الرعاية الصحية.",
    "transition": "النسخة العربية بصيغتها الجديدة قيد الإعداد. يمكنك قراءة المقال بالإنجليزية أو الفرنسية.",
    "english": "قراءة بالإنجليزية",
    "french": "قراءة بالفرنسية",
    "collection": "تصفح المجموعة بالإنجليزية",
    "by": "بقلم"
  }
};
